version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 3009
    depends_on:
      - web

  web:
    image: j73642/jacks-aiostreams:1.0.0@sha256:24fe7ea08bded96d2ccb5dc53bf1deeff0977291e3471f5d3aee79ff7d209eb5
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      PORT: 3009
      DATABASE_URI: sqlite://./data/aiostreams.db
      SECRET_KEY: ${APP_SEED}
      BASE_URL: http://${DEVICE_DOMAIN_NAME}:3009
      ADDON_NAME: AIOStreams
      ADDON_ID: jacks-aiostreams.umbrel
      LOG_LEVEL: info
      DISABLE_RATE_LIMITS: "true"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3009/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
